### ISSUE TITLE
429 Client Error: too_many_requests_for_device_id

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-amplitude-send#42]
````
429 Client Error: too_many_requests_for_device_id for url: https://api.amplitude.com/httpapi: HTTPError
Traceback (most recent call last):
File "/var/task/amplitude.py", line 60, in handle
process_compressed(pool, s3_object.get()["Body"].read())
File "/var/task/amplitude.py", line 226, in __exit__
raise self._err
````

I just saw this error flow through. When I looked at the device_ids, there was one that had a run of 356 and 637 events. I think it might've been @jrgm running load tests. But how should the script handle this? It means we'll never be able to submit this entire payload, that's for sure.

**Comment by jrgm** [comment]
Yeah, I was running a loadtest in stage. The client in that test does not send, for one thing, a `Accept-Language` header. A real browser **should**, but it's not required by the protocol.

**Comment by jrgm** [comment]
Oh, sorry. Too many requests. Hmm.

**Comment by jbuck** [comment]
Yeah, in this case if we try to send too many events with the same device_id it'll reject our payload. We've configured the lambda function to bail immediately if any error occurs, so we'll only be able to send the parts of the payload up until this long string of events happens.

**Comment by philbooth** [comment]
Just had a read of the docs and the relevant section is here:

https://amplitude.zendesk.com/hc/en-us/articles/204771828#http-status-codes-retrying-failed-requests

If we self-throttle to 10 events per second per device, there should be no problem. Plus there's a 30-second cool-down period after the 429 has been returned.

**Comment by philbooth** [comment]
@jbuck, are you still planning to port the import script to Node? If so, I'll probably hold off fixing this until that's merged, or if not I can PR a fix for the Python version.

**Comment by philbooth** [comment]
I've been playing around with implementing this in our current export script and it turns out that the rate-limit requirements from Amplitude do not play nicely with our desire to run statelessly from AWS Lambda.

The Amplitude docs say we should back off sending any more events for the offending `device_id` or `user_id` for 30 seconds before trying again. And, as far as I can tell, the error response doesn't indicate which `device_id` or `user_id` is the offender. At the moment we just lump devices and users together willy-nilly as they come to us from the logs, meaning we'd have to pause for every device and user from an offending batch. In a real 429 situation, I could easily picture this exploding into a cascade of delayed events that take us past the 5-minute limit for Lambda invocations.

Of course, we could mitigate that to some extent if we batched by `user_id` and/or `device_id`, as we'd then know which specific user/device we're pausing for. But even that wouldn't address the problem of statelessness between Lambda invocations. If we were throttled within 30 seconds of the next invocation, we'd have no way of communicating to that following invocation that it needs to pause for some ids.

There is an open email thread with Amplitude where they ask for our thoughts on making rate-limiting easier to handle, so I will go into all this with them there. But long term, it might be that Lambda is the wrong tool for the job here. Running statelessly might be making things more difficult for us than they need to be.

**Comment by philbooth** [comment]
> But even that wouldn't address the problem of statelessness between Lambda invocations.
>
> ...
>
> But long term, it might be that Lambda is the wrong tool for the job here.

Of course, we could just add state in the form of a Redis instance or whatever and keep the current set-up. No idea why I went dragging Lambda's name through the mud there, think I had tunnel vision from looking at the code and not thinking about the bigger picture.

**Comment by philbooth** [comment]
@jbuck, @rfk, what do you think about the following half-baked strawman proposal for a sane approach to rate-limiting our amplitude export?

#### Requirements

* MUST present the same interface to the logging pipeline. So it's still a Lambda function, invoked per-minute or whatever, and it processes the entire log chunk that it's invoked for within the 5-minute limit imposed by Lambda.

* MUST partition batches by `device_id` and `user_id` because that is how they are rate-limited and the 429 response doesn't indicate which ids exceeded the limit. We don't want to waste time and resources handling collateral damage.

* MUST partition batches between the HTTP and Identify APIs, because they have different rate-limits and are throttled independently.

* MUST perform backoff-and-retry logic outside of the regular Lambda process, because of potential clashes between Lambda's 5-minute threshold and the cooldown period.

#### Proposal

Change the current Lambda script so that it writes data to Redis. Run a new script (in multiple processes) in EC2 somewhere, have it read events from Redis and send them to Amplitude.

There would be four separate keyspaces in Redis:

* `http-device-${device_id}` for HTTP API payloads that have a `device_id` property.

* `http-user-${user_id}` for HTTP API payloads that don't have a `device_id` property.

* `identify-device-${device_id}` for Identify API payloads that have a `device_id` property.

* `identify-user-${user_id}` for Identify API payloads that don't have a `device_id` property.

The values stored in Redis would be objects with a format along the lines of:

```
{
  events: {Array},
  throttled: {Boolean}
}
```

Both scripts would use Redis' `WATCH`, `MULTI` and `EXEC` commands for safe concurrent updates, so that the Lambda script can run multi-threaded and the Amplitude-sending script can scale to as many processes as we need it to. Both scripts would contain retry logic in the event of a `WATCH` conflict.

The send script would iterate using `RANDOMKEY`. Before sending, it would check the `throttled` property. If set, it just yields instead of sends (so it's a nop).

On a 200 response, the sent events would be removed (as part of the `MULTI`), removing the key entirely if there are no other events. On a 429 response, it leaves the events in place but sets the `throttled` flag. Then it sets a timeout for the appropriate cooldown period, which will try to send again using the same key.

#### Other notes

* Much of the Lambda script can stay the same, just the batching logic needs to change and then it should write to Redis instead of sending to Amplitude. But the Lambda/S3/threading code doesn't need to change.

* I'm picturing the send script in Node, but it doesn't need to be.

* We don't need to do anything about this yet. But we'll probably need something in place before we make the switch to proper device ids. And if not then, definitely when we start sending more Sync events with those proper device ids.

* This all seemed simpler in my head, but now that I've written it down I wonder if I've overcomplicated it. Maybe there's something else that works as well or better with less moving parts.

* I did actually try to implement something simpler (from the outside) involving both Redis and Amplitude inside the Lambda script. But I couldn't see a way to get robust throttle/retry semantics in the presence of an arbitrary 5-minute cutoff.

Thoughts?

**Comment by rfk** [comment]
As an initial thought, I wonder if you could assume that most exports will succeed most of the time, and so have the primary script write only the *failed* batches into redis, and then a separate "retry script" that pulls failed batches out of redis and retries them.  It might help avoid overwhelming redis.

**Comment by jbuck** [comment]
This issue makes me want to stock my fingers in my ear and go "la la la I can't hear you there's nothing wrong" :)

I kinda want to wait and see what Amplitude can do for us first before making any more changes to our stuff.

**Comment by shane-tomlinson** [comment]
@jbuck, @philbooth - Is there anything additional we want to do here, or should we close this until Amplitude comes back to us and says we should take additional action?

**Comment by philbooth** [comment]
@shane-tomlinson I'd rather keep the issue open until we've either done something about it or handed off responsibility for the import process elsewhere. But also I don't have any plans to do anything about it in the short term at least, so if it's stinking up the backlog too much I don't mind if you want to close it.

**Comment by philbooth** [comment]
Amplitude's batch event API is now in beta, supports 1000 events per second per `device_id`:

https://developers.amplitude.com/?http#Batch-Event-Upload

**Comment by irrationalagent** [comment]
I have no clue about this one and whether or not its still occurring.

**Comment by clouserw** [comment]
@jbuck do you still see this error?
